### ISSUE TITLE
npm i

### ISSUE THREAD

**Issue by kiko20211** [AssaEmpireToken/BSC-Autotrade-Bot#1]
hello, I'm trying to install the dependencies with mpm i and I get this error:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: typescript@4.2.4
npm ERR! node_modules/typescript
npm ERR!   dev typescript@"^4.1.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer typescript@"^2.7 || ^3" from awesome-typescript-loader@5.2.1
npm ERR! node_modules/awesome-typescript-loader
npm ERR!   dev awesome-typescript-loader@"^5.2.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\franc\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\franc\AppData\Local\npm-cache\_logs\2022-05-26T06_46_46_826Z-debug-0.log

can you help me?

**Comment by AssaEmpireToken** [comment]
Have u try yarn?

**Comment by kiko20211** [comment]
friend, do you have telegram or some method to communicate, install npm but now when you start the bot it gives another error and I can't pass you a screenshot here.

**Comment by kiko20211** [comment]
ERROR in Entry module not found: Error: Can't resolve './src'

**Comment by AssaEmpireToken** [comment]
unfortunately i don't have a telegram... i think our programmer made a mistake here. I'll forward the bug first. if you are interested we have another pancakeswap prediction bot that works perfectly

**Comment by AssaEmpireToken** [comment]
try again now download it via source and then unpack and start again. I changed something again maybe it works now

**Comment by kiko20211** [comment]
ERROR in ./src/index.js 44:0
Module parse failed: The keyword 'enum' is reserved (44:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| })();
|
> enum TaskStep {
|     Selling,
|     Buying

**Comment by kiko20211** [comment]
does it work for you?

**Comment by AssaEmpireToken** [comment]
I dont use the bot. 
our programmer use the bot. 
i think our programmer made a mistake here. I'll forward the bug first. if you are interested we have another pancakeswap prediction bot that works perfectly
